# Generated by Django 4.0.5 on 2022-06-03 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='important',
            field=models.CharField(choices=[(1, 'not urgent'), (2, 'important'), (3, 'urgent')], default=(1, 'not urgent'), max_length=100),
        ),
    ]
