# Generated by Django 4.0.5 on 2022-06-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todo_datecomplited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='important',
            field=models.CharField(choices=[('not urgent', 'not urgent'), ('important', 'important'), ('urgent', 'urgent')], default=('not urgent', 'not urgent'), max_length=100),
        ),
    ]
