# Generated by Django 4.0.5 on 2022-06-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_todo_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='sometest',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
