# Generated by Django 4.0.5 on 2022-06-03 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_todo_sometest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='sometest',
        ),
    ]
