# Generated by Django 4.0.5 on 2022-06-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_remove_todo_sometest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='important',
            field=models.CharField(choices=[('white', 'not-urgent'), ('yellow', 'important'), ('red', 'urgent')], default=('white', 'not-urgent'), max_length=100),
        ),
    ]
