# Generated by Django 4.0.5 on 2022-06-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_alter_todo_important'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='important',
            field=models.CharField(choices=[('alert-secondary', 'common'), ('alert-warning', 'important'), ('alert-danger', 'very important')], default=('alert-secondary', 'common'), max_length=100),
        ),
    ]
